from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser #its role is to parse(analyse) output generated by a language model and ensure it is in the expected string format
from langchain_ollama.llms import OllamaLLM
import streamlit as st 
import os
from dotenv import load_dotenv

load_dotenv()

os.environ["LANGSMITH_TRACING"] = "true"
os.environ["LANGSMITH_API_KEY"] = os.getenv("LANGSMITH_API_KEY")

#Prompt-Template...
prompt = ChatPromptTemplate([
    ("system", "You are a helpful AI bot. Your name is D9AI. Created by Darshan. Please response to the user query in short"),
    ("user", "Question:{question}")
])

#Streamlit framework.....

st.title("D9AI")
input_text = st.text_input("Hi! How Can I Help You..")


# Ollama LLM...
llm = OllamaLLM(model="llama3.2:3b")
output_parser = StrOutputParser()
chain = prompt|llm|output_parser

if input_text:
    st.write(chain.invoke({"question":input_text}))